general:
    padding: 32
    channels : 3

train:
    batch_size : 32
    epochs : 150
    train_val_split : 0.7

    architecture : xmasnet
    use_augmentation : True

    callbacks:
        lr_reduce:
            apply : True
            use_default_params : False
            monitor : val_loss
            factor : 0.3
            patience : 5
            min_lr : 0.0001
            min_delta: 0.005
            cooldown: 5
            verbose : 1

        early_stopping:
            apply : False
            use_default_params : False
            monitor : val_loss
            min_delta : 0.00001
            patiente : 15
            verbose : 1
            mode : auto

    optimizers:
        use : sgd
        use_default_params : False
        lr : 0.000001
        decay : 0.2
        momentum : 0.7
        nesterov : True
        amsgrad : False
