general:
    padding: 32
    channels : 3

train:
    learning_rate : 0.001
    momentum : 0.0001
    batch_size : 15
    epochs : 200
    train_val_split : 0.7

    callbacks:
        lr_reduce_factor : 0.2
        lr_reduce_patience : 5
        lr_reduce_min_lr : 0.0001
        


Preprocessing:
    
