meta:
  registered_path :  data/interim/train_registered/
  unregistered_path : data/interim/train/

general:
  channels: 3
  padding: 32
preprocessing:
  apply: true
  augmented_ds_size: 300
  interpolation: cubic
  rescale: true
  rescale_method: standartize
train:
  batch_size: 16
  callbacks:
    early_stopping:
      apply: true
      min_delta: 1.0e-06
      mode: auto
      monitor: val_loss
      patience: 15
      use_default_params: false
      verbose: 1
    lr_reduce:
      apply: false
      cooldown: 5
      factor: 0.5
      min_delta: 0.001
      min_lr: 1.0e-07
      monitor: val_loss
      patience: 5
      use_default_params: false
      verbose: 2
  epochs: 100
  optimizers:
    amsgrad: false
    architecture: resnet
    decay: 0.001
    lr: 0.01
    momentum: 0.7
    nesterov: true
    use: rmsprop
    use_default_params: false
  train_val_split: 0.7
  use_augmentation: false
