general:
    padding: 32
    channels : 3

preprocessing:
    apply: True

    augmented_ds_size : 2500

    rescale: True
    rescale_method : standartize

train:
    batch_size : 32
    epochs : 400
    train_val_split : 0.7

    architecture : resnet
    use_augmentation : True

    callbacks:
        lr_reduce:
            apply : False
            use_default_params : False
            monitor : val_loss
            factor : 0.5
            patience : 5
            min_lr : 0.0001
            min_delta: 0.001
            cooldown: 5
            verbose : 2

        early_stopping:
            apply : False
            use_default_params : False
            monitor : val_loss
            min_delta : 0.00001
            patiente : 15
            verbose : 1
            mode : auto

    optimizers:
        use : sgd
        use_default_params : False
        lr : 0.000001
        decay : 0.3
        momentum : 0.99
        nesterov : False
        amsgrad : False
