general:
    padding: 32
    channels : 3

train:
    batch_size : 55
    epochs : 200
    train_val_split : 0.7

    callbacks:
        lr_reduce_aply : True
        lr_reduce_factor : 0.3
        lr_reduce_patience : 5
        lr_reduce_min_lr : 0.0001

    optimizers:
        use : adam
        use_default_params : False
        lr : 0.000002
        decay : 0.0001
        momentum : 0.00005
        nesterov : True
        amsgrad : False
