general:
  channels: 3
  padding: 32
meta:
  # exams_to_consider:
  # - tfl_3d PD ref_tra_1.5x1.5_t3
  # - t2_tse_tra
  # - KTrans
  exams_to_consider: [ t2_tse_tra, PD, ADC_tra]
  layers_path: models/intermediate_outputs/
  registered_path: data/interim/train_registered/
  unregistered_path: data/interim/train/
preprocessing:
  apply: true
  augmentation:
    histogram_method: None
  augmented_ds_size: 2500
  interpolation: cubic
  rescale: true
  rescale_method: normalize
train:
  batch_size: 16
  callbacks:
    early_stopping:
      apply: true
      min_delta: 0.001
      mode: auto
      monitor: val_loss
      patience: 5
      use_default_params: false
      verbose: 1
    lr_reduce:
      apply: false
      cooldown: 5
      factor: 0.5
      min_delta: 0.001
      min_lr: 1.0e-07
      monitor: val_loss
      patience: 5
      use_default_params: false
      verbose: 2
  epochs: 350
  optimizers:
    amsgrad: false
    architecture: vgg16
    decay: 0.0
    lr: 0.00001
    momentum: 0.0
    nesterov: false
    use: adam
    use_default_params: false
  train_val_split: 0.7
  use_augmentation: false
  use_gridsearch: false
