general:
  channels: 3
  padding: 32
meta:
  exams_to_consider:
  - t2_tse_tra
  - PD
  - ADC_tra
  layers_path: models/intermediate_outputs/
  registered_path: data/interim/train_registered/
  unregistered_path: data/interim/train/
preprocessing:
  apply: true
  augmentation:
    histogram_method: None
  augmented_ds_size: 2500
  interpolation: cubic
  rescale: true
  rescale_method: normalize
  use_augmentation: false
train:
  batch_size: 1
  callbacks:
    early_stopping:
      apply: true
      min_delta: 0.001
      mode: auto
      monitor: val_loss
      patience: 10
      use_default_params: false
      verbose: 1
    lr_reduce:
      apply: false
      cooldown: 5
      factor: 0.5
      min_delta: 0.001
      min_lr: 1.0e-07
      monitor: val_loss
      patience: 5
      use_default_params: false
      verbose: 2
  epochs: 10
  fit_model: true
  gridsearch_number_tries: 10
  n_runs: 10
  optimizers:
    amsgrad: false
    architecture: crfxmasnet
    crf_num_iterations: 5
    crf_theta_alpha: 0.5
    crf_theta_beta: 3.0
    crf_theta_gamma: 3.0
    crf_initializer: default
    decay: 0.001
    lr: 0.0001
    momentum: 0.0
    nesterov: true
    use: adam
    use_default_params: false
  save_intermediate_outputs: false
  train_val_split: 0.7
  use_gridsearch: false
  verbose : 1