general:
  channels: 3
  padding: 32
meta:
  exams_to_consider:
  - t2_tse_tra
  - PD
  - ADC_tra
  layers_path: models/intermediate_outputs/
  registered_path: data/interim/train_registered/
  unregistered_path: data/interim/train/
preprocessing:
  apply: true
  augmentation:
    histogram_method: None
  augmented_ds_size: 2500
  interpolation: cubic
  rescale: true
  rescale_method: normalize
train:
  batch_size: 16
  callbacks:
    early_stopping:
      apply: true
      min_delta: 0.001
      mode: auto
      monitor: loss
      patience: 5
      use_default_params: false
      verbose: 1
    lr_reduce:
      apply: false
      cooldown: 5
      factor: 0.5
      min_delta: 0.001
      min_lr: 1.0e-07
      monitor: val_loss
      patience: 5
      use_default_params: false
      verbose: 2
  epochs: 10
  gridsearch_number_tries: 40
  n_runs: 5
  optimizers:
    amsgrad: false
    architecture: xmasnet
    decay: 0.999
    lr: 1.0e-05
    momentum: 0.99
    nesterov: false
    use: sgd
    use_default_params: false
  train_val_split: 0.7
  use_augmentation: false
  use_gridsearch: true
